name: Publish to Github Pages
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout/@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate VC vocabularies
        run: |
          npm install yml2vocab
          npm update yml2vocab
          ./node_modules/.bin/yml2vocab -v vocab/credentials/v2/vocabulary.yml -t vocab/credentials/v2/template.html
      - name: Publish to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          branch: gh-pages
          folder: .
          git-config-name: "vcwg[bot]"
          git-config-email: "vcwg[bot]@users.noreply.github.com"
          single-commit: true
